name: Lint & Format Check (Backend & Frontend)

on:
  pull_request:
    branches:
      - main  # Run checks on PRs to main

jobs:
  backend-lint-format:
    name: Backend - Ruff Lint & Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend  # Set working directory for Python job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Match with ruff.toml

      - name: Install Dependencies
        run: |
          pip install ruff pre-commit

      - name: Run Ruff Formatting Check
        run: ruff format --check .

      - name: Run Ruff Linting
        run: ruff check .

      - name: Run Pre-commit Hooks
        run: pre-commit run --all-files

  frontend-lint-format:
    name: Frontend - React.js ESLint & Prettier
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend  # Set working directory for React job

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint (Linting)
        run: npx eslint . || true

      - name: Run Prettier (Formatting)
        run: npx prettier --check .
